### PR TITLE
CUP-2291 Create a New Story to Verify a User Can search For Their Com…

### PR DESCRIPTION
**Pull request by TrailsH**
…pany

**[DESCRIPTION OF CHANGES]**
1. Created pages file for DUNSManagerPages
2. Created a GetADUNSpage class
4. Created GetADunsSteps file

**[EXTRA CONSIDERATIONS WHEN REVIEWING CODE]**

1. Anyting else important to consider when reviewing this code?

**[TESTING STEPS TAKEN]**

1. How was this tested? Screenshots to support?

QA
image
Stg
image

image

**[ASSOCIATED ISSUE]**

https://github.com/dandb/phoenix/issues/##

https://dunandb.jira.com/browse/CUP-2291

### CODE REVIEW

**Comment by saihareesu** [comment]
@TrailsH can you please add all stories pass screenshot in the How was this tested? Screenshots to support? step

**Comment by saihareesu** [comment]
@TrailsH This code needs to be rebased

**Comment by saihareesu** [comment]
Can you please add all stories screenshot in the step How was this tested? Screenshots to support?

**Comment by TrailsH** [comment]
Added screenshot for AllStories

**Comment by saihareesu** [comment]
Closing this PR, as all these changes are accounted in https://github.com/NijeshChandran/regression/pull/17

**Pull request closed without merging**
